server/db/models/category.js
server/db/models/index.js

---
Created category model for database

feat: create category model

---

server/api/categories.js
server/api/index.js

---
Created 'categories' api route and initialized it with a get request for '/api/categories'.

Created the categories api route file and linked it to index.js

---

client/components/ProductList.js
client/components/SingleProductSnapshot.js
client/components/index.js
client/routes.js
client/store/index.js
client/store/products.js
public/style.css
server/api/products.js

---
- Create 'products' reducer to store product list.
- Create ProductList component that fetches products from database and puts them on redux state.
- Create SingleProductSnapshot component that displays the image, name, and price of a single product.
- Map over products from database and render a snapshot of each product.
- Create a route to display ProductList (/products)

feature: view all products by manually navigating to /products

---

server/db/models/product.js

---
Change data type for product price to decimal from integer

bug: enabled decimals for product price

---

client/components/ProductList.js
client/components/SingleProductDetail.js
client/store/index.js
client/store/singleProduct.js

---
_Your PR Notes Here_
Took some time to fix some of the merge conflicts, still working on the single product view, will keep working on it

first try single product view

---

client/components/navbar.js

---
Cart icon wasn't showing after logging in. Now it does. Bug fixed.

Cart icon now displays when logged in. Bug fixed.

---

client/components/ProductList.js
client/store/index.js

bug fix: import store/products

---

client/components/CategoryList.js
client/components/SingleCategorySnapshot.js
client/components/guest-home.js
client/components/user-home.js
client/store/categories.js
client/store/index.js
public/style.css
script/seed.js

---
Created and properly hooked the category reducer.
Created the CategoryList component, styled it and rendered it in the home page.

Category reducer added. CategoryList component created and styled.

---

client/components/SingleProductSnapshot.js
public/style.css

---
* Style the SingleProductSnapshot component a little.
* Added the caption (sliced from the description) by implementing a helper function. 
* Added commas to the prices by implementing a second helper function.
* Added the star icons (hardcoded) for future use when working with making reviews.

Styles added to the SingleProductSnapshot component.

---

client/components/SingleProductDetail.js
client/components/SingleProductSnapshot.js
public/style.css

---
* Linked the SingleProduct component to the ProductSnapshot.
* Added extra elements to the ProductSnapshot component and also fixed and styled the layout.

Linked the SingleProduct component to the now styled ProductSnapshot.

---

client/components/CategoryList.js
client/components/Dropdown.js
client/components/ProductList.js
client/components/ProductsNav.js
public/style.css

---
* Made the Categories List dropdown menu and the most popular links work properly.
* Added respective style.

CategoriesList dropdown menu up and running.

---

client/components/AddProductForm.js
client/components/CategoryList.js
client/components/EditProductForm.js
client/components/ProductList.js
client/components/SingleProductDetail.js
client/routes.js
server/api/products.js

* Added category selection to add product form.
* Added links for add product and edit product forms.
* Bug fix: category list did not render with page refresh or manual URL navigation
* Refactored the ternary in ProductList to eliminate duplicate .map callback

Enable category selection on add product form #25

---

client/components/SingleProductDetail.js

* Bug fix: edit product form did not pre-populate properly

bugfix: pre-populate edit product form

---

client/components/CategoryList.js
server/api/products.js

Sorry guys, I tested it more thoroughly before submitting this one.
* Edit Product form did not properly re-render page.

bugfix: edit product did not rerender page properly

---

client/components/Cart.js
client/components/navbar.js
server/api/orders.js

---
_Your PR Notes Here_
Not sure how, but my style.css didn't merge to master on Friday, so I'll have to do the css part again

minor edits now cart component rendered properly

---

client/store/cart.js
server/api/cart.js
server/db/models/index.js

---
Stuck on Cart model and querying it. May not be set up right. Sharing progress with Enrique following our phone discussion.

passing off progress to enrique. routes do not work for cart

---

server/api/index.js
server/api/orders.js
server/api/users.js
server/db/models/address.js
server/db/models/category.js
server/db/models/index.js
server/db/models/order.js
server/db/models/orderitem.js
server/db/models/review.js
server/db/models/user.js

---
* Refactored a few models: Order, OrderItem, Category, Review, Address, and User.
* Added a couple of API routes.

Order and OrderItem models added.

---

client/components/Profile.js
client/routes.js
client/store/user.js
server/api/addresses.js

---
- Profile component created in order to display all the user related features like: Account Details, History, Addresses, etc. 
- Component only accesible when logged in.

Created a Profile component in order to link the User related features

---

client/components/Cart.js
client/store/cart.js
client/store/products.js

passing off

---

client/components/Cart.js
client/components/OrderItemSnapshot.js
public/style.css

---
- Made changes with Cara on the Cart Component.
- Created the OrderItemSnapshot component and linked it to the cart component.

Few changes made to Cart component

---

client/components/SingleProductDetail.js
client/store/cart.js
server/api/cart.js
server/api/index.js
server/auth/index.js
server/index.js

---
* Updated cart reducer to store unique products and an associated order quantity.
* Cart is stored on state and on req.session.cart for guests.
* Need to work on storing cart on DB for logged in user and retrieving carts for both guests and authenticated users.

Guest sessions

---

script/seed.js
server/db/models/index.js

---
- Added extra data for the additional models like: Addresses, Orders, and OrderItems.

Additional models seeding

---

client/components/Cart.js
client/components/OrderItemSnapshot.js

---
Cart reducer is now an object. Renders in Cart component with quantity.
Steps remaining: 
Write cart to database for authenticated users
Update quantities from the cart, (and remove from cart)

bugfix: converted cart object to array for Cart component rendering

---

client/components/Cart.js
client/components/OrderItemSnapshot.js
client/components/navbar.js
client/routes.js
client/store/cart.js
public/style.css
server/api/cart.js
server/api/users.js

---
As a developer I wan to have access to the cart from state in the Navbar, in order to display the amount of items it carries.

Fetching cart in navbar

---

client/components/Cart.js
client/components/OrderItemSnapshot.js
client/store/cart.js
client/store/user.js
server/api/cart.js
server/auth/index.js
server/index.js

---
Bugfixes we discussed. Still working on cart reducer and adding/fetching

Bugfix: logout issue and rendering cart on first login

---

client/components/Cart.js
client/components/OrderItemSnapshot.js
client/components/navbar.js
client/store/cart.js
client/store/products.js
server/api/cart.js

---
* Guests can remove products from cart
* Working on removing products for logged in users

Remove from cart for guests

---

client/components/SingleProductDetail.js
client/store/cart.js
client/store/user.js

---
* can select quantity to add to cart
* cart in navbar goes back to 0 upon logout

feat: set quantity to add to cart

---

client/components/AddToCartPopup.js
client/components/Cart.js
client/components/OrderItemSnapshot.js
client/components/SingleProductDetail.js
public/style.css
script/seed.js

- Added styles to a few features in the Cart like: popupWindow background, cart items, quantity select tag.

Cart styles added

---

client/components/SingleCategorySnapshot.js
client/components/SingleProductDetail.js
client/components/SingleProductSnapshot.js
public/style.css

- Added styles to the Categories and Products component for better UX.

Feat: Styles added to Categories and Products view.

---

client/components/OrderItemSnapshot.js
client/components/Profile.js
client/components/SingleProductDetail.js
client/components/navbar.js
client/routes.js
client/store/user.js
server/api/products.spec.js
server/index.js

* Added tests for products routes - GET, POST, and PUT
* Fixed bug with logout and dispatching 2 actions
* Deleted commented out code and unused variables

tests: added tests for products route

---

client/components/CompletedOrders.js
client/components/OrderHistory.js
client/components/Profile.js
client/routes.js
public/style.css

- Created the OrderHistory component to render the user's completed orders.
- Linked OrderHistory with the user's Profile.
- Style both components.

Feat: Rendering order history
